@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "orders" as order {
    *id : number <<PK>> <<generated>>
    --
    ...
}

entity "cfds" as cfd {
  *id : number <<PK>> <<generated>>
  --
  *order_id : text <<FK>>
  --
  quantity_usd: long
  creation_timestamp: Date
}

entity "cfd_states" as cfd_states {
    *id : number <<PK>> <<generated>>
    --
    state: blob
}
note left: state de-/serialized \nfrom rust state enum \nthis is not backwards\ncompatible, but that's \nOK for the MVP


order ||--|| cfd

cfd ||--|{ cfd_states


@enduml