use std::marker::PhantomData;
use xtra_productivity::xtra_productivity;

struct ActorWithParam<C> {
    ty: PhantomData<C>,
}

struct DummyMessage;

trait Foo {}

impl<C: 'static + Send> xtra::Actor for ActorWithParam<C> {}

// Dummy actor, xtra::Handler and xtra::Message impls generated by xtra_productivity
#[xtra_productivity]
impl<C> ActorWithParam<C>
where
    C: Foo,
{
    pub fn handle_dummy_message(&mut self, _message: DummyMessage) {
        assert_impls_foo::<C>();
    }
}

fn assert_impls_foo<T: Foo>() {}

fn main() {}
